### ISSUE TITLE
Aircraft will not start up in FG 2016.2.1 Mac

### ISSUE THREAD

**Issue by CA1012** [FGMEMBERS/A340-600HGW#1]
The aircraft will not start in 2016.2.1 mac. unless there is a way to manually start it, the aircraft is not capable of flying

**Comment by FGDATA** [comment]
That's very surprising Falcon @CA1012 
I just launched in Linux, it launches just fine

**Comment by FGDATA** [comment]
@CA1012 
I just tested a departure.
The A340-600HGW is in very good operating conditions :8ball: 

![fgfs-screen-447](https://cloud.githubusercontent.com/assets/10859459/15829394/799b3e94-2bc8-11e6-9be3-22396805be7e.png)

**Comment by CA1012** [comment]
As i said in the initial comment, its a mac launcher issue. I think i will need to wait until 2016.3 to fly again. :(

**Comment by FGDATA** [comment]
maybe you may want to try my launcher? it is a text-editor based launcher that invokes the command line. I never tried it on Macos, but I dont see why it wouldn't work.

If it is the difference between flying or not flying, I'll say its worth trying.

**Comment by CA1012** [comment]
Don't think it will work.

**Comment by FGDATA** [comment]
and I don't know. but certainly would try out.

Have you talkd to T-URBO? I think he is succesfully behind a Mac.

**Comment by CA1012** [comment]
I have not been on mumble alot recently.

**Comment by CA1012** [comment]
but i can look

**Comment by FGDATA** [comment]
maybe I can jump in quick later today.

**Comment by CA1012** [comment]
that would help a lot.

**Comment by IAHM-COL** [comment]
bummer I couldn't today
I am still out.
Tomorrow Maybe?

**Comment by CA1012** [comment]
Lets see if we can meet today about that.

**Comment by FGDATA** [comment]
that's a good plan
Not too late thou. Like 730 our time
